apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: l60t5ukc3-go
  janus-idp.io/tekton: l60t5ukc3-go
  backstage.io/kubernetes-id: l60t5ukc3-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: l60t5ukc3-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
